# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from actuator/Actuator.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Actuator(genpy.Message):
  _md5sum = "0a5f96192a9e0f688db79bb649c89f55"
  _type = "actuator/Actuator"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 strDirec
uint8 strAng
uint8 accDire
uint8 accVal

uint8 left = 0
uint8 right = 1
uint8 back = 0
uint8 forward = 1
"""
  # Pseudo-constants
  left = 0
  right = 1
  back = 0
  forward = 1

  __slots__ = ['strDirec','strAng','accDire','accVal']
  _slot_types = ['uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       strDirec,strAng,accDire,accVal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Actuator, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.strDirec is None:
        self.strDirec = 0
      if self.strAng is None:
        self.strAng = 0
      if self.accDire is None:
        self.accDire = 0
      if self.accVal is None:
        self.accVal = 0
    else:
      self.strDirec = 0
      self.strAng = 0
      self.accDire = 0
      self.accVal = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.strDirec, _x.strAng, _x.accDire, _x.accVal))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.strDirec, _x.strAng, _x.accDire, _x.accVal,) = _get_struct_4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.strDirec, _x.strAng, _x.accDire, _x.accVal))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.strDirec, _x.strAng, _x.accDire, _x.accVal,) = _get_struct_4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
