// Generated by gencpp from file ultra_sonic/Ultra_dis.msg
// DO NOT EDIT!


#ifndef ULTRA_SONIC_MESSAGE_ULTRA_DIS_H
#define ULTRA_SONIC_MESSAGE_ULTRA_DIS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ultra_sonic
{
template <class ContainerAllocator>
struct Ultra_dis_
{
  typedef Ultra_dis_<ContainerAllocator> Type;

  Ultra_dis_()
    : fr(0.0)
    , re(0.0)  {
    }
  Ultra_dis_(const ContainerAllocator& _alloc)
    : fr(0.0)
    , re(0.0)  {
  (void)_alloc;
    }



   typedef float _fr_type;
  _fr_type fr;

   typedef float _re_type;
  _re_type re;





  typedef boost::shared_ptr< ::ultra_sonic::Ultra_dis_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ultra_sonic::Ultra_dis_<ContainerAllocator> const> ConstPtr;

}; // struct Ultra_dis_

typedef ::ultra_sonic::Ultra_dis_<std::allocator<void> > Ultra_dis;

typedef boost::shared_ptr< ::ultra_sonic::Ultra_dis > Ultra_disPtr;
typedef boost::shared_ptr< ::ultra_sonic::Ultra_dis const> Ultra_disConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ultra_sonic::Ultra_dis_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ultra_sonic::Ultra_dis_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ultra_sonic::Ultra_dis_<ContainerAllocator1> & lhs, const ::ultra_sonic::Ultra_dis_<ContainerAllocator2> & rhs)
{
  return lhs.fr == rhs.fr &&
    lhs.re == rhs.re;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ultra_sonic::Ultra_dis_<ContainerAllocator1> & lhs, const ::ultra_sonic::Ultra_dis_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ultra_sonic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ultra_sonic::Ultra_dis_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ultra_sonic::Ultra_dis_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ultra_sonic::Ultra_dis_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ultra_sonic::Ultra_dis_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ultra_sonic::Ultra_dis_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ultra_sonic::Ultra_dis_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ultra_sonic::Ultra_dis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ee497f682fbf9bc21a5c9d264d23864";
  }

  static const char* value(const ::ultra_sonic::Ultra_dis_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ee497f682fbf9bcULL;
  static const uint64_t static_value2 = 0x21a5c9d264d23864ULL;
};

template<class ContainerAllocator>
struct DataType< ::ultra_sonic::Ultra_dis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ultra_sonic/Ultra_dis";
  }

  static const char* value(const ::ultra_sonic::Ultra_dis_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ultra_sonic::Ultra_dis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 fr\n"
"float32 re\n"
;
  }

  static const char* value(const ::ultra_sonic::Ultra_dis_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ultra_sonic::Ultra_dis_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fr);
      stream.next(m.re);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ultra_dis_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ultra_sonic::Ultra_dis_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ultra_sonic::Ultra_dis_<ContainerAllocator>& v)
  {
    s << indent << "fr: ";
    Printer<float>::stream(s, indent + "  ", v.fr);
    s << indent << "re: ";
    Printer<float>::stream(s, indent + "  ", v.re);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ULTRA_SONIC_MESSAGE_ULTRA_DIS_H
