// Generated by gencpp from file snbird/Whls_vel.msg
// DO NOT EDIT!


#ifndef SNBIRD_MESSAGE_WHLS_VEL_H
#define SNBIRD_MESSAGE_WHLS_VEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace snbird
{
template <class ContainerAllocator>
struct Whls_vel_
{
  typedef Whls_vel_<ContainerAllocator> Type;

  Whls_vel_()
    : fl(0.0)
    , fr(0.0)
    , rl(0.0)
    , rr(0.0)  {
    }
  Whls_vel_(const ContainerAllocator& _alloc)
    : fl(0.0)
    , fr(0.0)
    , rl(0.0)
    , rr(0.0)  {
  (void)_alloc;
    }



   typedef float _fl_type;
  _fl_type fl;

   typedef float _fr_type;
  _fr_type fr;

   typedef float _rl_type;
  _rl_type rl;

   typedef float _rr_type;
  _rr_type rr;





  typedef boost::shared_ptr< ::snbird::Whls_vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snbird::Whls_vel_<ContainerAllocator> const> ConstPtr;

}; // struct Whls_vel_

typedef ::snbird::Whls_vel_<std::allocator<void> > Whls_vel;

typedef boost::shared_ptr< ::snbird::Whls_vel > Whls_velPtr;
typedef boost::shared_ptr< ::snbird::Whls_vel const> Whls_velConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snbird::Whls_vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snbird::Whls_vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::snbird::Whls_vel_<ContainerAllocator1> & lhs, const ::snbird::Whls_vel_<ContainerAllocator2> & rhs)
{
  return lhs.fl == rhs.fl &&
    lhs.fr == rhs.fr &&
    lhs.rl == rhs.rl &&
    lhs.rr == rhs.rr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::snbird::Whls_vel_<ContainerAllocator1> & lhs, const ::snbird::Whls_vel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace snbird

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::snbird::Whls_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snbird::Whls_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snbird::Whls_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snbird::Whls_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snbird::Whls_vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snbird::Whls_vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snbird::Whls_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "291d0a1bb554e9cecb818a219ca75ef0";
  }

  static const char* value(const ::snbird::Whls_vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x291d0a1bb554e9ceULL;
  static const uint64_t static_value2 = 0xcb818a219ca75ef0ULL;
};

template<class ContainerAllocator>
struct DataType< ::snbird::Whls_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snbird/Whls_vel";
  }

  static const char* value(const ::snbird::Whls_vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snbird::Whls_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 fl\n"
"float32 fr\n"
"float32 rl\n"
"float32 rr\n"
;
  }

  static const char* value(const ::snbird::Whls_vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snbird::Whls_vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fl);
      stream.next(m.fr);
      stream.next(m.rl);
      stream.next(m.rr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Whls_vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snbird::Whls_vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snbird::Whls_vel_<ContainerAllocator>& v)
  {
    s << indent << "fl: ";
    Printer<float>::stream(s, indent + "  ", v.fl);
    s << indent << "fr: ";
    Printer<float>::stream(s, indent + "  ", v.fr);
    s << indent << "rl: ";
    Printer<float>::stream(s, indent + "  ", v.rl);
    s << indent << "rr: ";
    Printer<float>::stream(s, indent + "  ", v.rr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNBIRD_MESSAGE_WHLS_VEL_H
